using System;
using System.IO;
using System.Linq;
using KingdomTycoon.Presentation.Raids;
using KingdomTycoon.UI;
using TMPro;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEditor.Events;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;
using Object = UnityEngine.Object;

namespace KingdomTycoon.Editor
{
    public static class P14RaidSetup
    {
        public const string Root = "Assets/KingdomTycoon/ContentGenerated/P14Raids";
        public const string ScreenPath = Root + "/Prefabs/P14_RAID_SCREEN.prefab";
        public const string MarkerPath = Root + "/P14Raids.marker.asset";
        public const string BootstrapScenePath = "Assets/KingdomTycoon/Scenes/Bootstrap.unity";
        public const string Fingerprint = "P14-RAID-UI-v1.0.0";
        public static readonly string[] RequiredIds = { "P14_RAID_SCREEN", "P14_HEADER", "P14_CLOSE", "P14_RAID_1", "P14_RAID_6", "P14_MEMBER_1", "P14_MEMBER_8", "P14_PART_1", "P14_PART_4", "P14_BOSS_HP_FILL", "P14_DEPLOY", "P14_WARNING", "P14_RESULT", "P14_TRACE" };

        [MenuItem("Kingdom Tycoon/P14/Generate Raid Assets")]
        public static void Run() { ValidateContent(); GenerateScreen(); IntegrateBootstrapScene(); P14GeneratedAssetVerifier.Verify(); Debug.Log("P14_SETUP_COMPLETED"); }
        public static void ValidateContent()
        {
            string manifest = Path.GetFullPath(Path.Combine(UnityEngine.Application.dataPath, "StreamingAssets", "Content", "1.0.0-content.12", "content_manifest.json"));
            if (!File.Exists(manifest)) throw new BuildFailedException("P14_CONTENT_MANIFEST_MISSING"); string text = File.ReadAllText(manifest);
            if (!text.Contains("\"contentVersion\":\"1.0.0-content.12\"", StringComparison.Ordinal) || !text.Contains("\"csvSchemaSetVersion\":10", StringComparison.Ordinal)) throw new BuildFailedException("P14_CONTENT_MANIFEST_INVALID");
            string directory = Path.GetDirectoryName(manifest) ?? throw new BuildFailedException("P14_CONTENT_PATH_INVALID"); foreach (string file in new[] { "raids.csv", "raid_difficulties.csv", "raid_parts.csv", "raid_unlock_rules.csv", "raid_role_requirements.csv", "raid_part_target_rules.csv", "raid_boss_phase_rules.csv" }) if (!File.Exists(Path.Combine(directory, file))) throw new BuildFailedException("P14_CONTENT_TABLE_MISSING: " + file);
        }

        private static void GenerateScreen()
        {
            EnsureFolder(Root); EnsureFolder(Root + "/Prefabs");
            var root = new GameObject("P14_RAID_SCREEN", typeof(RectTransform), typeof(Canvas), typeof(CanvasScaler), typeof(GraphicRaycaster), typeof(CanvasGroup), typeof(RaidScreenPresenter)); RectTransform rect = root.GetComponent<RectTransform>(); rect.sizeDelta = new Vector2(1920, 1080);
            Canvas canvas = root.GetComponent<Canvas>(); canvas.renderMode = RenderMode.ScreenSpaceOverlay; canvas.sortingOrder = 96; CanvasScaler scaler = root.GetComponent<CanvasScaler>(); scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize; scaler.referenceResolution = new Vector2(1920, 1080); scaler.matchWidthOrHeight = .5f; CanvasGroup group = root.GetComponent<CanvasGroup>();
            Image background = Panel("Background", root.transform, new Color32(7, 13, 16, 255)); Stretch(background.rectTransform); Image top = Panel("BronzeTop", background.transform, new Color32(53, 37, 24, 255)); Rect(top.rectTransform, new Vector2(0, .91f), Vector2.one);
            Image safe = Panel("SafeArea", root.transform, new Color32(15, 24, 27, 250)); Rect(safe.rectTransform, new Vector2(.018f, .028f), new Vector2(.982f, .972f));
            Text("Eyebrow", safe.transform, "왕실 레이드 지휘소  ·  콘텐츠 12", 17, TextAlignmentOptions.Left, new Vector2(.022f, .938f), new Vector2(.52f, .985f), new Color32(112, 214, 192, 255));
            Text("P14_HEADER", safe.transform, "왕국 레이드 지휘소", 40, TextAlignmentOptions.Left, new Vector2(.022f, .86f), new Vector2(.38f, .945f), new Color32(246, 211, 124, 255));
            Text("Season", safe.transform, "지역 보스 토벌  ·  6~8인 원정대  ·  부위 파괴", 19, TextAlignmentOptions.Right, new Vector2(.48f, .88f), new Vector2(.93f, .94f), new Color32(165, 189, 182, 255));
            Button close = Button("P14_CLOSE", safe.transform, "×", new Color32(80, 53, 43, 255), 34); Rect(close.GetComponent<RectTransform>(), new Vector2(.94f, .89f), new Vector2(.985f, .975f));

            Image raidRail = Panel("RaidRail", safe.transform, new Color32(22, 34, 36, 255)); Rect(raidRail.rectTransform, new Vector2(.018f, .055f), new Vector2(.21f, .85f)); Text("RaidRailTitle", raidRail.transform, "토벌 작전", 22, TextAlignmentOptions.Left, new Vector2(.08f, .91f), new Vector2(.92f, .98f), new Color32(212, 185, 112, 255));
            var raidButtons = new Button[6]; var raidLabels = new TMP_Text[6]; string[] names = { "늪의 히드라\n<size=17>일반 · 권장 1,800</size>", "늪의 히드라\n<size=17>고난 · 권장 2,700</size>", "늪의 히드라\n<size=17>타락 · 권장 4,050</size>", "재의 고룡\n<size=17>일반 · 권장 3,000</size>", "재의 고룡\n<size=17>고난 · 권장 4,500</size>", "재의 고룡\n<size=17>타락 · 권장 6,750</size>" };
            for (int i = 0; i < 6; i++) { raidButtons[i] = Button($"P14_RAID_{i + 1}", raidRail.transform, names[i], i == 0 ? new Color32(92, 130, 66, 255) : new Color32(38, 49, 50, 255), 20); Rect(raidButtons[i].GetComponent<RectTransform>(), new Vector2(.07f, .77f - i * .135f), new Vector2(.93f, .885f - i * .135f)); raidLabels[i] = raidButtons[i].GetComponentInChildren<TMP_Text>(); }

            Image arena = Panel("Arena", safe.transform, new Color32(24, 31, 33, 255)); Rect(arena.rectTransform, new Vector2(.22f, .055f), new Vector2(.70f, .85f)); TMP_Text title = Text("BossTitle", arena.transform, "늪의 히드라  <size=24><color=#9FCFC2>일반</color></size>", 35, TextAlignmentOptions.Left, new Vector2(.04f, .89f), new Vector2(.78f, .98f), new Color32(244, 210, 124, 255));
            TMP_Text briefing = Text("Briefing", arena.transform, "제한 시간 5:00  ·  편성 6~8명  ·  최고 기록 없음", 18, TextAlignmentOptions.Right, new Vector2(.31f, .89f), new Vector2(.96f, .96f), new Color32(160, 184, 178, 255));
            Image bossFrame = Panel("BossFrame", arena.transform, new Color32(31, 48, 37, 255)); Rect(bossFrame.rectTransform, new Vector2(.04f, .49f), new Vector2(.96f, .87f)); Image bossAura = Panel("BossAura", bossFrame.transform, new Color32(70, 102, 54, 190)); Rect(bossAura.rectTransform, new Vector2(.34f, .08f), new Vector2(.66f, .92f)); TMP_Text bossGlyph = Text("BossGlyph", bossAura.transform, "□\n<size=19>맹독 다두수</size>", 72, TextAlignmentOptions.Center, Vector2.zero, Vector2.one, new Color32(232, 206, 113, 255));
            Image hpTrack = Panel("BossHpTrack", bossFrame.transform, new Color32(17, 22, 23, 255)); Rect(hpTrack.rectTransform, new Vector2(.08f, .06f), new Vector2(.92f, .13f)); Image hpFill = Panel("P14_BOSS_HP_FILL", hpTrack.transform, new Color32(98, 162, 76, 255)); Rect(hpFill.rectTransform, Vector2.zero, Vector2.one); Text("BossHpText", hpTrack.transform, "우두머리 체력  100%", 17, TextAlignmentOptions.Center, Vector2.zero, Vector2.one);
            var partButtons = new Button[4]; var partLabels = new TMP_Text[4]; string[] partNames = { "머리\n<size=15>독 숨결 약화</size>", "몸통\n<size=15>방어력 감소</size>", "심장\n<size=15>격노 유발</size>", "예비 표적" }; for (int i = 0; i < 4; i++) { partButtons[i] = Button($"P14_PART_{i + 1}", arena.transform, partNames[i], i == 0 ? new Color32(92, 130, 66, 255) : new Color32(43, 54, 53, 255), 19); Rect(partButtons[i].GetComponent<RectTransform>(), new Vector2(.04f + i * .235f, .38f), new Vector2(.255f + i * .235f, .47f)); partLabels[i] = partButtons[i].GetComponentInChildren<TMP_Text>(); }
            Image tactical = Panel("TacticalPanel", arena.transform, new Color32(18, 27, 29, 255)); Rect(tactical.rectTransform, new Vector2(.04f, .055f), new Vector2(.96f, .35f)); TMP_Text result = Text("P14_RESULT", tactical.transform, "<color=#9FCFC2><b>작전 대기</b></color>\n표적 부위와 원정대를 확인한 뒤 출정하세요.", 21, TextAlignmentOptions.TopLeft, new Vector2(.04f, .46f), new Vector2(.96f, .92f)); TMP_Text trace = Text("P14_TRACE", tactical.transform, "00.0초  원정대 편성 대기\n--.-초  보스 단계 추적 준비", 17, TextAlignmentOptions.TopLeft, new Vector2(.04f, .08f), new Vector2(.96f, .43f), new Color32(139, 169, 162, 255));

            Image partyPanel = Panel("PartyPanel", safe.transform, new Color32(27, 37, 39, 255)); Rect(partyPanel.rectTransform, new Vector2(.71f, .055f), new Vector2(.985f, .85f)); TMP_Text partyCount = Text("PartyCount", partyPanel.transform, "원정대 0 / 8", 27, TextAlignmentOptions.Left, new Vector2(.06f, .90f), new Vector2(.64f, .98f), new Color32(241, 207, 119, 255)); Text("RoleGuide", partyPanel.transform, "탱커 · 힐러 · 원거리", 16, TextAlignmentOptions.Right, new Vector2(.44f, .91f), new Vector2(.94f, .97f), new Color32(141, 181, 170, 255));
            var memberButtons = new Button[8]; var memberLabels = new TMP_Text[8]; for (int i = 0; i < 8; i++) { memberButtons[i] = Button($"P14_MEMBER_{i + 1}", partyPanel.transform, $"<b>원정대원 {i + 1}</b>  {(i % 3 == 0 ? "수호자" : i % 3 == 1 ? "성직자" : "궁수")}\n<size=16>정예 · 전투력 {410 + i * 23} · 물약 2</size>", new Color32(45, 58, 57, 255), 19); Rect(memberButtons[i].GetComponent<RectTransform>(), new Vector2(.05f, .80f - i * .086f), new Vector2(.95f, .882f - i * .086f)); memberLabels[i] = memberButtons[i].GetComponentInChildren<TMP_Text>(); }
            TMP_Text warning = Text("P14_WARNING", partyPanel.transform, "<color=#F1B36A>주의 · 탱커 없음 · 힐러 없음</color>", 17, TextAlignmentOptions.Center, new Vector2(.05f, .11f), new Vector2(.95f, .18f)); Button deploy = Button("P14_DEPLOY", partyPanel.transform, "최소 6명을 편성하세요", new Color32(151, 89, 45, 255), 22); Rect(deploy.GetComponent<RectTransform>(), new Vector2(.05f, .025f), new Vector2(.95f, .105f)); TMP_Text deployLabel = deploy.GetComponentInChildren<TMP_Text>();

            RaidScreenView view = safe.gameObject.AddComponent<RaidScreenView>(); view.Configure(group, close, raidButtons, raidLabels, memberButtons, memberLabels, partButtons, partLabels, title, briefing, partyCount, warning, result, trace, bossFrame, bossAura, bossGlyph, hpFill, deploy, deployLabel); root.GetComponent<RaidScreenPresenter>().Configure(view);
            PrefabUtility.SaveAsPrefabAsset(root, ScreenPath); Object.DestroyImmediate(root); P14GeneratedAssetMarker marker = AssetDatabase.LoadAssetAtPath<P14GeneratedAssetMarker>(MarkerPath); if (marker == null) { marker = ScriptableObject.CreateInstance<P14GeneratedAssetMarker>(); AssetDatabase.CreateAsset(marker, MarkerPath); } marker.fingerprint = Fingerprint; EditorUtility.SetDirty(marker); AssetDatabase.SaveAssets(); AssetDatabase.Refresh(ImportAssetOptions.ForceSynchronousImport);
        }
        private static void IntegrateBootstrapScene()
        {
            Scene scene = EditorSceneManager.OpenScene(BootstrapScenePath, OpenSceneMode.Single); CommonUiRoot common = Object.FindFirstObjectByType<CommonUiRoot>(FindObjectsInactive.Include) ?? throw new BuildFailedException("P14_COMMON_UI_ROOT_MISSING"); Transform screens = common.transform.Find("ScreenCanvas") ?? throw new BuildFailedException("P14_SCREEN_CANVAS_MISSING"); foreach (Transform old in screens.Cast<Transform>().Where(value => value.name == "P14_RAID_SCREEN").ToArray()) Object.DestroyImmediate(old.gameObject);
            GameObject prefab = AssetDatabase.LoadAssetAtPath<GameObject>(ScreenPath) ?? throw new BuildFailedException("P14_UI_PREFAB_MISSING"); GameObject root = (GameObject)PrefabUtility.InstantiatePrefab(prefab, screens); root.name = "P14_RAID_SCREEN"; PrepareRoot(root); RaidScreenPresenter presenter = root.GetComponent<RaidScreenPresenter>(); root.SetActive(false);
            Transform hud = common.transform.Find("HudCanvas/SafeArea") ?? throw new BuildFailedException("P14_HUD_SAFE_AREA_MISSING"); Transform existing = hud.Find("P14_RAID_NAV_BUTTON"); if (existing != null) Object.DestroyImmediate(existing.gameObject); Button button = Button("P14_RAID_NAV_BUTTON", hud, "레이드", new Color32(132, 62, 52, 255), 22); RectTransform br = button.GetComponent<RectTransform>(); br.anchorMin = br.anchorMax = new Vector2(.79f, 0); br.offsetMin = new Vector2(0, 110); br.offsetMax = new Vector2(182, 190); RaidEntryButton entry = button.gameObject.AddComponent<RaidEntryButton>(); entry.Configure(presenter, button); UnityEventTools.AddPersistentListener(button.onClick, entry.OpenRaids); EditorSceneManager.MarkSceneDirty(scene); EditorSceneManager.SaveScene(scene);
        }
        internal static void PrepareRoot(GameObject root) { RectTransform rect = root.GetComponent<RectTransform>(); rect.localScale = Vector3.one; rect.anchorMin = rect.anchorMax = rect.pivot = new Vector2(.5f, .5f); rect.anchoredPosition = Vector2.zero; rect.sizeDelta = new Vector2(1920, 1080); CanvasGroup group = root.GetComponent<CanvasGroup>(); if (group != null) group.alpha = 1; }
        internal static void Capture(GameObject root, string directory, string filename, int width, int height)
        {
            root.SetActive(true); PrepareRoot(root); RectTransform rootRect = root.GetComponent<RectTransform>(); rootRect.sizeDelta = new Vector2(width, height); rootRect.position = Vector3.zero; Canvas canvas = root.GetComponent<Canvas>(); canvas.enabled = true;
            var cameraObject = new GameObject("P14CaptureCamera", typeof(Camera)); Camera camera = cameraObject.GetComponent<Camera>(); camera.clearFlags = CameraClearFlags.SolidColor; camera.backgroundColor = new Color32(7, 13, 16, 255); camera.orthographic = true; camera.orthographicSize = height / 2f; camera.nearClipPlane = .1f; camera.farClipPlane = 100f; camera.aspect = width / (float)height; camera.transform.position = new Vector3(0, 0, -10); camera.transform.rotation = Quaternion.identity;
            var target = new RenderTexture(width, height, 24, RenderTextureFormat.ARGB32); target.Create(); camera.targetTexture = target; canvas.renderMode = RenderMode.WorldSpace; canvas.worldCamera = camera; Canvas.ForceUpdateCanvases(); RenderTexture previous = RenderTexture.active; RenderTexture.active = target; GL.Clear(true, true, camera.backgroundColor); camera.Render(); var texture = new Texture2D(width, height, TextureFormat.RGB24, false); texture.ReadPixels(new Rect(0, 0, width, height), 0, 0); texture.Apply(false, false); string path = Path.Combine(directory, filename); File.WriteAllBytes(path, texture.EncodeToPNG()); RenderTexture.active = previous; camera.targetTexture = null; target.Release(); Object.DestroyImmediate(target); Object.DestroyImmediate(texture); Object.DestroyImmediate(cameraObject); canvas.renderMode = RenderMode.ScreenSpaceOverlay; canvas.worldCamera = null; if (new FileInfo(path).Length <= 100000) throw new BuildFailedException("P14_CAPTURE_FAILED: " + filename);
        }
        private static Image Panel(string name, Transform parent, Color color) { var go = new GameObject(name, typeof(RectTransform), typeof(Image)); go.transform.SetParent(parent, false); Image image = go.GetComponent<Image>(); image.color = color; return image; }
        private static TMP_Text Text(string name, Transform parent, string value, float size, TextAlignmentOptions alignment, Vector2 min, Vector2 max, Color? color = null) { var go = new GameObject(name, typeof(RectTransform), typeof(TextMeshProUGUI)); go.transform.SetParent(parent, false); TMP_Text text = go.GetComponent<TMP_Text>(); text.text = value; text.fontSize = size; text.alignment = alignment; text.color = color ?? new Color32(238, 231, 214, 255); text.textWrappingMode = TextWrappingModes.Normal; text.overflowMode = TextOverflowModes.Overflow; text.raycastTarget = false; Rect(text.rectTransform, min, max); return text; }
        private static Button Button(string name, Transform parent, string label, Color color, float size) { Image image = Panel(name, parent, color); Button button = image.gameObject.AddComponent<Button>(); button.targetGraphic = image; ColorBlock colors = button.colors; colors.highlightedColor = Color.Lerp(color, Color.white, .12f); colors.pressedColor = Color.Lerp(color, Color.black, .16f); colors.disabledColor = new Color(color.r * .55f, color.g * .55f, color.b * .55f, .72f); button.colors = colors; Text("Label", image.transform, label, size, TextAlignmentOptions.Center, Vector2.zero, Vector2.one); return button; }
        private static void Stretch(RectTransform value) => Rect(value, Vector2.zero, Vector2.one); private static void Rect(RectTransform value, Vector2 min, Vector2 max) { value.anchorMin = min; value.anchorMax = max; value.offsetMin = value.offsetMax = Vector2.zero; }
        private static void EnsureFolder(string path) { string current = "Assets"; foreach (string segment in path.Split('/').Skip(1)) { string next = current + "/" + segment; if (!AssetDatabase.IsValidFolder(next)) AssetDatabase.CreateFolder(current, segment); current = next; } }
    }

    public static class P14GeneratedAssetVerifier
    {
        [MenuItem("Kingdom Tycoon/P14/Verify Generated Assets")]
        public static void Verify()
        {
            P14RaidSetup.ValidateContent(); P14GeneratedAssetMarker marker = AssetDatabase.LoadAssetAtPath<P14GeneratedAssetMarker>(P14RaidSetup.MarkerPath); if (marker == null || marker.fingerprint != P14RaidSetup.Fingerprint) throw new BuildFailedException("P14_GENERATED_FINGERPRINT_INVALID"); GameObject prefab = AssetDatabase.LoadAssetAtPath<GameObject>(P14RaidSetup.ScreenPath) ?? throw new BuildFailedException("P14_UI_PREFAB_MISSING"); Transform[] nodes = prefab.GetComponentsInChildren<Transform>(true); foreach (string id in P14RaidSetup.RequiredIds) if (nodes.Count(value => value.name == id) != 1) throw new BuildFailedException("P14_UI_ID_INVALID: " + id); prefab.SetActive(true); P14RaidSetup.PrepareRoot(prefab); Canvas.ForceUpdateCanvases(); string[] invalid = prefab.GetComponentsInChildren<Button>(true).Where(value => value.GetComponent<RectTransform>().rect.width < 64 || value.GetComponent<RectTransform>().rect.height < 64).Select(value => value.name).ToArray(); prefab.SetActive(false); if (invalid.Length > 0) throw new BuildFailedException("P14_TOUCH_TARGET_INVALID: " + string.Join(",", invalid)); Scene scene = EditorSceneManager.OpenScene(P14RaidSetup.BootstrapScenePath, OpenSceneMode.Single); RaidScreenPresenter[] screens = scene.GetRootGameObjects().SelectMany(value => value.GetComponentsInChildren<RaidScreenPresenter>(true)).ToArray(); RaidEntryButton[] entries = scene.GetRootGameObjects().SelectMany(value => value.GetComponentsInChildren<RaidEntryButton>(true)).ToArray(); if (screens.Length != 1 || entries.Length != 1) throw new BuildFailedException($"P14_SCENE_ENTRY_INVALID: screens={screens.Length}, entries={entries.Length}"); Button button = entries[0].GetComponent<Button>(); if (button == null || button.onClick.GetPersistentEventCount() != 1 || button.onClick.GetPersistentTarget(0) != entries[0]) throw new BuildFailedException("P14_SCENE_ENTRY_BINDING_INVALID"); Debug.Log("P14_ASSETS_VERIFIED");
        }
    }

    public static class P14CaptureGenerator
    {
        [MenuItem("Kingdom Tycoon/P14/Generate Acceptance Captures")]
        public static void Run()
        {
            P14GeneratedAssetVerifier.Verify(); Scene scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single); GameObject root = (GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>(P14RaidSetup.ScreenPath), scene); root.SetActive(true); P14RaidSetup.PrepareRoot(root); Transform[] nodes = root.GetComponentsInChildren<Transform>(true); string output = Path.GetFullPath(Path.Combine(UnityEngine.Application.dataPath, "..", "..", "docs", "reports", "captures", "P14")); Directory.CreateDirectory(output); P14RaidSetup.Capture(root, output, "p14_01_hydra_prep.png", 1920, 1080);
            nodes.Single(value => value.name == "P14_BOSS_HP_FILL").GetComponent<RectTransform>().anchorMax = new Vector2(.63f, 1); nodes.Single(value => value.name == "P14_RESULT").GetComponent<TMP_Text>().text = "<color=#F4D27A><b>전투 진행 중</b></color>  02:14\n히드라 몸통 파괴 · 방어력 감소 활성"; nodes.Single(value => value.name == "P14_TRACE").GetComponent<TMP_Text>().text = "12.0초  맹독 이빨  생명력 58,400\n48.0초  몸통 파괴  생명력 41,200\n74.0초  독성 숨결  생명력 32,500"; P14RaidSetup.Capture(root, output, "p14_02_hydra_combat.png", 1920, 1080);
            nodes.Single(value => value.name == "P14_BOSS_HP_FILL").GetComponent<RectTransform>().anchorMax = new Vector2(0, 1); nodes.Single(value => value.name == "P14_RESULT").GetComponent<TMP_Text>().text = "<color=#F4D27A><b>토벌 성공</b></color>  184.3초\n파괴 부위: 머리, 몸통 · 보상: 히드라 심장 x1"; P14RaidSetup.Capture(root, output, "p14_03_hydra_result.png", 1920, 1080);
            nodes.Single(value => value.name == "P14_RAID_1").GetComponent<Image>().color = new Color32(38, 49, 50, 255); nodes.Single(value => value.name == "P14_RAID_4").GetComponent<Image>().color = new Color32(137, 60, 55, 255); nodes.Single(value => value.name == "BossTitle").GetComponent<TMP_Text>().text = "재의 고룡  <size=24><color=#E8A49B>일반</color></size>"; nodes.Single(value => value.name == "Briefing").GetComponent<TMP_Text>().text = "제한 시간 6:00  ·  편성 6~8명  ·  최고 기록 212.6초"; nodes.Single(value => value.name == "BossFrame").GetComponent<Image>().color = new Color32(47, 31, 35, 255); nodes.Single(value => value.name == "BossAura").GetComponent<Image>().color = new Color32(126, 47, 45, 210); nodes.Single(value => value.name == "BossGlyph").GetComponent<TMP_Text>().text = "△\n<size=19>잿빛 하늘의 폭군</size>"; nodes.Single(value => value.name == "P14_BOSS_HP_FILL").GetComponent<Image>().color = new Color32(173, 67, 61, 255); nodes.Single(value => value.name == "P14_BOSS_HP_FILL").GetComponent<RectTransform>().anchorMax = new Vector2(0, 1); string[] dragonParts = { "뿔\n<size=15>돌진 약화</size>", "날개\n<size=15>비행 봉쇄</size>", "몸통\n<size=15>방어력 감소</size>", "심장\n<size=15>최종 격노</size>" }; for (int index = 0; index < 4; index++) nodes.Single(value => value.name == $"P14_PART_{index + 1}").GetComponentInChildren<TMP_Text>().text = dragonParts[index]; nodes.Single(value => value.name == "P14_RESULT").GetComponent<TMP_Text>().text = "<color=#F4D27A><b>1차 결말 해금</b></color>\n재의 고룡 토벌 완료 · 변형 레이드 개방"; nodes.Single(value => value.name == "P14_TRACE").GetComponent<TMP_Text>().text = "42.0초  뿔 파괴  생명력 142,300\n118.0초  비행 봉쇄  생명력 86,900\n212.6초  잿빛 고룡 토벌"; P14RaidSetup.Capture(root, output, "p14_04_dragon_ending.png", 1920, 1080); P14RaidSetup.Capture(root, output, "p14_05_20x9.png", 2400, 1080); Debug.Log($"P14_CAPTURES={output}; count=5");
        }
    }

    public static class P14AndroidBuilder
    {
        [MenuItem("Kingdom Tycoon/P14/Build Android Development APK")]
        public static void Build() { P14GeneratedAssetVerifier.Verify(); string output = Path.GetFullPath(Path.Combine(UnityEngine.Application.dataPath, "..", "Builds", "Android", "KingdomTycoon-P14-Development.apk")); Directory.CreateDirectory(Path.GetDirectoryName(output) ?? throw new InvalidOperationException("P14_ANDROID_OUTPUT_INVALID")); PlayerSettings.SetScriptingBackend(UnityEditor.Build.NamedBuildTarget.Android, ScriptingImplementation.IL2CPP); PlayerSettings.Android.targetArchitectures = AndroidArchitecture.ARM64; BuildReport report = BuildPipeline.BuildPlayer(new BuildPlayerOptions { scenes = EditorBuildSettings.scenes.Where(value => value.enabled).Select(value => value.path).ToArray(), locationPathName = output, target = BuildTarget.Android, targetGroup = BuildTargetGroup.Android, options = BuildOptions.Development }); if (report.summary.result != BuildResult.Succeeded || !File.Exists(output)) throw new BuildFailedException($"P14 Android build failed: {report.summary.result}, errors={report.summary.totalErrors}"); Debug.Log($"P14_ANDROID_APK={output}; bytes={new FileInfo(output).Length}"); }
    }

    internal sealed class P14RaidBuildGuard : IPreprocessBuildWithReport { public int callbackOrder => 140; public void OnPreprocessBuild(BuildReport report) => P14GeneratedAssetVerifier.Verify(); }
}
